// front/src/components/CartModal.vue
<template>
  <teleport to="body">
    <div class="modal-overlay" @click.self="onClose">
      <div class="modal-content">
        <header class="modal-header">
          <h3>Carrito</h3>
          <button class="close-btn" @click="onClose">✕</button>
        </header>

        <div v-if="items.length === 0" class="empty-cart">
          El carrito está vacío
        </div>
        <div v-else>
          <div v-for="item in items" :key="item._id" class="cart-item">
            <img :src="getImageUrl(item)" :alt="item.name" />
            <div class="cart-item-info">
              <h4 class="cart-item-name">{{ item.name }}</h4>
              <p class="cart-item-price">€{{ item.price }}</p>
            </div>
            <div class="cart-quantity">
              <button @click="$emit('decrease', item)">-</button>
              <input
                type="number"
                :value="item.quantity"
                @input="
                  $emit(
                    'updateQuantity',
                    item,
                    parseInt($event.target.value) || 0
                  )
                "
                @blur="
                  $emit(
                    'updateQuantity',
                    item,
                    parseInt($event.target.value) || 0
                  )
                "
                :min="0"
                class="quantity-input"
              />
              <button @click="$emit('increase', item)">+</button>
            </div>
          </div>
          <div class="cart-total">Total: €{{ total.toFixed(2) }}</div>
          <button class="checkout-button" @click="$emit('checkout')">
            Finalizar compra
          </button>
        </div>
      </div>
    </div>
  </teleport>
</template>

<script setup>
import { defineProps, defineEmits } from "vue";

const props = defineProps({
  items: { type: Array, required: true },
  total: { type: Number, required: true },
});

const emit = defineEmits([
  "close",
  "increase",
  "decrease",
  "updateQuantity",
  "checkout",
]);
import { buildImageUrl } from "../api/urls";

function onClose() {
  emit("close");
}

function getImageUrl(product) {
  if (!product.image) return "/placeholder.png";
  if (product.image.startsWith("http")) return product.image;
  return buildImageUrl(product.image);
}
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal-content {
  background: #ffffff;
  border: 1px solid #e0e0e0;
  border-radius: 12px;
  width: 520px;
  max-width: 95vw;
  max-height: 85vh;
  overflow: auto;
  padding: 20px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}

.modal-header h3 {
  color: #4247c1;
  margin: 0;
}

.close-btn {
  background: #f0f0f5;
  color: #1c1c29;
  border: none;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s;
}

.close-btn:hover {
  background: #e0e0e0;
}

.empty-cart {
  text-align: center;
  padding: 40px 0;
  color: #1c1c29;
}

.cart-item {
  display: flex;
  align-items: center;
  padding: 12px 0;
  border-bottom: 1px solid #e0e0e0;
}

.cart-item img {
  max-width: 150px;
  max-height: 105px;
  width: auto;
  height: auto;
  object-fit: contain;
  margin-right: 12px;
  background: #f8f9fa;
  border-radius: 6px;
  padding: 8px;
}

.cart-item-info {
  flex-grow: 1;
}

.cart-item-name {
  font-size: 0.95rem;
  margin: 0;
  color: #1c1c29;
  font-weight: 500;
}

.cart-item-price {
  color: var(--primary-color);
  margin-top: 4px;
  font-weight: 600;
}

.cart-quantity {
  display: flex;
  align-items: center;
  gap: 8px;
}

.cart-quantity button {
  background: #f0f0f5;
  border: 1px solid #e0e0e0;
  color: #1c1c29;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1rem;
  font-weight: 600;
}

.cart-quantity button:hover {
  background: #4247c1;
  color: #ffffff;
  border-color: #4247c1;
}

.quantity-input {
  width: 50px;
  height: 28px;
  text-align: center;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  background: #ffffff;
  color: #1c1c29;
  font-size: 0.95rem;
  font-weight: 500;
  padding: 0 4px;
  box-sizing: border-box;
}

.quantity-input:focus {
  outline: none;
  border-color: #4247c1;
  box-shadow: 0 0 0 2px rgba(66, 71, 193, 0.1);
}

.quantity-input::-webkit-outer-spin-button,
.quantity-input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.quantity-input[type="number"] {
  -moz-appearance: textfield;
  appearance: textfield;
}

.cart-total {
  margin-top: 16px;
  text-align: right;
  font-weight: bold;
  color: #1c1c29;
  font-size: 1.1rem;
}

.checkout-button {
  width: 100%;
  background: var(--primary-color);
  color: #ffffff;
  border: none;
  padding: 12px;
  border-radius: 6px;
  margin-top: 12px;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.2s;
}

.checkout-button:hover {
  background: #3539a0;
  transform: translateY(-1px);
}
</style>

// front/src/components/CartModal.svelte
<script>
  import { onMount } from 'svelte';
  import { buildImageUrl } from '../api/urls.js';
  import {
    cartItems,
    checkout,
    itemCount,
    removeFromCart,
    total,
    updateQuantity,
  } from '../state/cartStore.js';
  import { addToast } from '../state/toastStore.js';

  let { open = false, onClose } = $props();

  let checkoutLoading = $state(false);
  let checkoutError = $state('');

  function close() {
    checkoutError = '';
    if (typeof onClose === 'function') onClose();
  }

  async function onCheckout() {
    if (checkoutLoading) return;
    checkoutError = '';
    checkoutLoading = true;

    try {
      const res = await checkout();
      if (!res.success) {
        checkoutError = res.error || 'Error al hacer checkout';
        addToast({ type: 'error', message: checkoutError, duration: 4000 });
        return;
      }
      addToast({ type: 'success', message: 'Compra realizada correctamente', duration: 3000 });
      close();
    } catch (e) {
      checkoutError = e?.message || 'Error al hacer checkout';
      addToast({ type: 'error', message: checkoutError, duration: 4000 });
    } finally {
      checkoutLoading = false;
    }
  }
</script>

{#if open}
  <div class="backdrop" role="dialog" aria-modal="true" on:click={close}>
    <div class="modal" on:click|stopPropagation>
      <div class="header">
        <div>
          <h2>Tu carrito</h2>
          <p class="muted">{String($itemCount)} artículo(s)</p>
        </div>
        <button class="close" type="button" on:click={close} aria-label="Cerrar">
          ×
        </button>
      </div>

      {#if $cartItems.length === 0}
        <div class="empty">
          <p>Tu carrito está vacío.</p>
          <button class="primary" type="button" on:click={close}>Seguir comprando</button>
        </div>
      {:else}
        <div class="items">
          {#each $cartItems as item (item._id)}
            <div class="item">
              <div class="thumb">
                <img
                  src={buildImageUrl(item?.image)}
                  alt={item?.name || 'Producto'}
                  loading="lazy"
                />
              </div>

              <div class="body">
                <div class="row">
                  <div class="name">{item?.name}</div>
                  <div class="line-total">€{(Number(item?.price || 0) * Number(item?.quantity || 0)).toFixed(2)}</div>
                </div>

                <div class="row controls">
                  <div class="qty">
                    <button
                      class="step"
                      type="button"
                      on:click={() => updateQuantity(item._id, Number(item.quantity || 0) - 1)}
                      disabled={Number(item.quantity || 0) <= 1}
                    >
                      -
                    </button>
                    <div class="qty-value">{item.quantity}</div>
                    <button
                      class="step"
                      type="button"
                      on:click={() => updateQuantity(item._id, Number(item.quantity || 0) + 1)}
                      disabled={Number(item.quantity || 0) >= Number(item.stock ?? Infinity)}
                    >
                      +
                    </button>
                  </div>

                  <button
                    class="remove"
                    type="button"
                    on:click={() => removeFromCart(item._id)}
                  >
                    Quitar
                  </button>
                </div>
              </div>
            </div>
          {/each}
        </div>

        <div class="footer">
          <div class="total">
            Total: <strong>€{$total.toFixed(2)}</strong>
          </div>

          <div class="footer-actions">
            <button class="secondary" type="button" on:click={close} disabled={checkoutLoading}>
              Seguir navegando
            </button>
            <button class="primary" type="button" on:click={onCheckout} disabled={checkoutLoading}>
              {checkoutLoading ? 'Procesando...' : 'Finalizar compra'}
            </button>
          </div>
        </div>
      {/if}

      {#if checkoutError}
        <div class="error" role="alert">{checkoutError}</div>
      {/if}
    </div>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.55);
    z-index: 2600;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 16px;
  }

  .modal {
    width: 100%;
    max-width: 980px;
    max-height: 85vh;
    overflow: auto;
    background: #fff;
    border: 1px solid rgba(224, 224, 224, 0.95);
    border-radius: 18px;
    box-shadow: 0 30px 90px rgba(0, 0, 0, 0.28);
  }

  .header {
    padding: 16px 16px 10px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 12px;
    border-bottom: 1px solid rgba(224, 224, 224, 0.9);
  }

  h2 {
    margin: 0 0 6px;
    font-size: 1.5rem;
    color: var(--secondary-color);
  }

  .muted {
    margin: 0;
    color: rgba(28, 28, 41, 0.7);
  }

  .close {
    width: 40px;
    height: 40px;
    border-radius: 12px;
    border: none;
    background: rgba(28, 28, 41, 0.06);
    cursor: pointer;
    font-size: 24px;
    line-height: 40px;
    font-weight: 900;
    color: rgba(28, 28, 41, 0.7);
  }

  .items {
    padding: 14px 16px 10px;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .item {
    border: 1px solid var(--border-color);
    border-radius: 16px;
    padding: 12px;
    display: grid;
    grid-template-columns: 120px 1fr;
    gap: 12px;
    background: rgba(66, 71, 193, 0.03);
  }

  .thumb {
    border-radius: 14px;
    border: 1px solid rgba(224, 224, 224, 0.8);
    overflow: hidden;
    aspect-ratio: 16/10;
    display: grid;
    place-items: center;
    background: rgba(66, 71, 193, 0.05);
  }

  .thumb img {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }

  .body {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .row {
    display: flex;
    justify-content: space-between;
    gap: 10px;
    align-items: center;
  }

  .controls {
    justify-content: space-between;
  }

  .name {
    font-weight: 900;
    color: rgba(28, 28, 41, 0.95);
  }

  .line-total {
    font-weight: 1000;
    color: var(--primary-color);
    white-space: nowrap;
  }

  .qty {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .step {
    width: 40px;
    height: 40px;
    border-radius: 12px;
    border: 1px solid rgba(224, 224, 224, 0.95);
    background: #fff;
    cursor: pointer;
    font-weight: 900;
    color: rgba(28, 28, 41, 0.75);
  }

  .step:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .qty-value {
    font-weight: 1000;
    min-width: 20px;
    text-align: center;
  }

  .remove {
    border: none;
    background: rgba(255, 107, 107, 0.1);
    color: #d32f2f;
    padding: 10px 12px;
    border-radius: 12px;
    font-weight: 900;
    cursor: pointer;
    white-space: nowrap;
  }

  .footer {
    padding: 12px 16px 16px;
    border-top: 1px solid rgba(224, 224, 224, 0.9);
    display: flex;
    justify-content: space-between;
    gap: 12px;
    align-items: center;
    flex-wrap: wrap;
  }

  .total {
    font-weight: 900;
    color: rgba(28, 28, 41, 0.85);
  }

  .footer-actions {
    display: flex;
    gap: 10px;
    align-items: center;
  }

  .secondary {
    background: rgba(28, 28, 41, 0.06);
    border: 1px solid rgba(28, 28, 41, 0.14);
    color: var(--secondary-color);
    padding: 12px 14px;
    border-radius: 12px;
    font-weight: 900;
    cursor: pointer;
  }

  .primary {
    border: none;
    background: var(--primary-color);
    color: #fff;
    padding: 12px 14px;
    border-radius: 12px;
    font-weight: 1000;
    cursor: pointer;
  }

  .primary:disabled,
  .secondary:disabled {
    opacity: 0.7;
    cursor: not-allowed;
  }

  .empty {
    padding: 22px 16px;
    text-align: center;
    color: rgba(28, 28, 41, 0.75);
  }

  .empty p {
    margin: 0 0 12px;
  }

  .error {
    padding: 0 16px 16px;
    color: #d32f2f;
    font-weight: 900;
  }

  @media (max-width: 720px) {
    .item {
      grid-template-columns: 1fr;
    }
    .thumb {
      aspect-ratio: 16/10;
    }
  }
</style>
